import { StrategyDef } from "../types";

const td = (n: number, key: string, name: string, description: string, params: StrategyDef["params"]): StrategyDef => ({
  id: `td_${String(n).padStart(2, "0")}_${key}`, name, family: "trader_discovery", description, params,
});

const prop = (n: number, key: string, name: string, description: string, params: StrategyDef["params"]): StrategyDef => ({
  id: `prop_${String(n).padStart(2, "0")}_${key}`, name, family: "proprietary", description, params,
});

export const TRADER_STRATEGIES: StrategyDef[] = [
  td(1, "h24_top5", "24h Top 5", "Copy bags of top 5 24h PnL traders.", { window: "24h", topN: 5 }),
  td(2, "h24_top3", "24h Top 3", "Copy bags of top 3 24h traders.", { window: "24h", topN: 3 }),
  td(3, "h24_top1", "24h #1 Only", "Mirror the single 24h leader.", { window: "24h", topN: 1 }),
  td(4, "d7_top5", "7d Top 5", "Copy weekly PnL leaders.", { window: "7d", topN: 5 }),
  td(5, "d7_top10", "7d Top 10 Thin", "Broader weekly watch, thinner clips.", { window: "7d", topN: 10, sizeScale: 0.5 }),
  td(6, "d30_top5", "30d Top 5", "Copy monthly leaders.", { window: "30d", topN: 5 }),
  td(7, "all_top5", "All-time Top 5", "Copy all-time leaders.", { window: "all", topN: 5 }),
  td(8, "all_top3", "All-time Top 3", "Elite all-time handles.", { window: "all", topN: 3 }),
  td(9, "multi_24_7", "24h∩7d Consistency", "Traders on both 24h and 7d boards.", { require: "h24_and_d7", topN: 5 }),
  td(10, "multi_7_30", "7d∩30d Consistency", "On weekly and monthly boards.", { require: "d7_and_d30", topN: 5 }),
  td(11, "triple", "Triple Window", "On 24h, 7d, and 30d boards.", { require: "h24_d7_d30", topN: 3 }),
  td(12, "mid_7d", "7d Mid Tier", "Ranks 6–15 weekly.", { window: "7d", rankFrom: 6, rankTo: 15, topN: 5 }),
  td(13, "mid_30d", "30d Mid Tier", "Ranks 10–25 monthly.", { window: "30d", rankFrom: 10, rankTo: 25, topN: 5 }),
  td(14, "anti_lb", "Anti-Leaderboard", "Ranks 30–50 control cohort.", { window: "7d", rankFrom: 30, rankTo: 50, topN: 5 }),
  td(15, "followers", "Follower Whales", "Prefer high follower counts.", { window: "7d", score: "followers", topN: 5 }),
  td(16, "eff", "PnL Efficiency", "Rank by pnl/volume.", { window: "7d", score: "pnl_over_vol", topN: 5 }),
  td(17, "risk_adj", "Risk-adj Proxy", "pnl/sqrt(volume).", { window: "30d", score: "pnl_sqrt_vol", topN: 5 }),
  td(18, "active", "Active Tape", "High trade-count leaders.", { window: "24h", score: "trades", topN: 5 }),
  td(19, "selective", "Selective Snipers", "Low trade count, high PnL.", { window: "7d", score: "selective", topN: 5 }),
  td(20, "sol", "Solana Bag Copy", "Copy Solana holdings only.", { window: "7d", chain: "solana", topN: 5 }),
  td(21, "base", "Base Bag Copy", "Copy Base holdings only.", { window: "7d", chain: "base", topN: 5 }),
  td(22, "eth", "ETH Bag Copy", "Copy Ethereum holdings only.", { window: "7d", chain: "ethereum", topN: 5 }),
  td(23, "top_only", "Largest Bag Only", "Only each leader #1 token.", { window: "7d", mode: "top_holding_only", topN: 5 }),
  td(24, "top3", "Diversified Bags", "Up to 3 tokens per leader.", { window: "7d", mode: "top3_holdings", topN: 5 }),
  td(25, "winners", "Winning Bags", "Only tokens with positive trader PnL.", { window: "7d", mode: "winning_tokens", topN: 5 }),
  td(26, "fade_lose", "Fade Loser Bags", "Sell tokens with negative trader PnL.", { window: "24h", mode: "fade_losing_tokens", topN: 5 }),
  td(27, "fresh", "Fresh 24h Rotation", "Re-pick daily board each tick.", { window: "24h", topN: 5 }),
  td(28, "stable", "Stable All∩30d", "All-time and monthly overlap.", { require: "all_and_d30", topN: 5 }),
  td(29, "breakout", "24h Breakouts", "Strong 24h, not all-time top.", { mode: "h24_not_all", topN: 5 }),
  td(30, "climbers", "Weekly Climbers", "On 7d but not deep on 30d.", { mode: "d7_not_d30", topN: 5 }),
  td(31, "vol", "Volume Leaders", "Highest volumeUsd.", { window: "7d", score: "volume", topN: 5 }),
  td(32, "pnl_floor", "PnL Floor", "7d pnl > $50k.", { window: "7d", minPnl: 50000, topN: 5 }),
  td(33, "pnl_band", "PnL Band", "7d pnl $10k–$200k.", { window: "7d", minPnl: 10000, maxPnl: 200000, topN: 5 }),
  td(34, "second", "Second Wave", "Ranks 4–12.", { window: "7d", rankFrom: 4, rankTo: 12, topN: 5 }),
  td(35, "consensus", "Crowd Consensus", "Tokens held by ≥3 watched traders.", { window: "7d", mode: "consensus", topN: 8 }),
  td(36, "unique", "Solo Alpha", "Tokens unique to one top trader.", { window: "7d", mode: "unique_bags", topN: 5 }),
  td(37, "thin", "Thin Copy", "Top 8 with half size.", { window: "7d", topN: 8, sizeScale: 0.5 }),
  td(38, "conc", "Concentrated Copy", "Top 2 only, full clips.", { window: "7d", topN: 2 }),
  td(39, "social", "Social Proof", "Followers ≥ 10k.", { window: "7d", minFollowers: 10000, topN: 5 }),
  td(40, "micro", "Micro Influencers", "Followers under 5k.", { window: "7d", maxFollowers: 5000, topN: 5 }),
  td(41, "wide", "Wide Books", "Traders with many holdings.", { window: "7d", score: "holdings", topN: 5 }),
  td(42, "tight", "Tight Books", "Few holdings, focused bags.", { window: "7d", score: "tight_books", topN: 5 }),
  td(43, "blend", "Blend 24h+7d", "Mix daily and weekly leaders.", { mode: "blend_h24_d7", topN: 6 }),
  td(44, "persist", "Persistence Score", "Appearances across windows.", { score: "persistence", topN: 5 }),
  td(45, "quint", "Quintile Diversify", "One trader per 7d quintile.", { window: "7d", mode: "quintiles", topN: 5 }),
  td(46, "fade_hot", "Fade 24h Hot Hands", "Avoid/sell what 24h leaders hold.", { window: "24h", mode: "fade_bags", topN: 5 }),
  td(47, "copy_trim", "Copy + Trim", "Buy leader bags, trim losers.", { window: "7d", mode: "copy_trim", topN: 5 }),
  td(48, "hi_val", "Highest Value Bags", "Prefer largest USD holdings.", { window: "7d", mode: "highest_value", topN: 5 }),
  td(49, "broad", "Broad Watch 15", "15 weekly names, thin size.", { window: "7d", topN: 15, sizeScale: 0.4 }),
  td(50, "hybrid", "Hybrid Elite", "All-time top ∩ 7d top.", { require: "all_and_d7", topN: 5 }),
];

export const PROP_STRATEGIES: StrategyDef[] = [
  prop(1, "consensus_buy", "Consensus Buy", "Buy tokens held by many leaders.", { mode: "consensus_buy", minHolders: 3 }),
  prop(2, "consensus_fade", "Consensus Fade", "Fade crowded leader bags.", { mode: "consensus_fade", minHolders: 4 }),
  prop(3, "top_pnl", "Top PnL Token", "Buy highest aggregate trader pnl token.", { mode: "top_pnl_token" }),
  prop(4, "worst_pnl", "Worst PnL Fade", "Sell/avoid worst aggregate pnl token.", { mode: "worst_pnl_token" }),
  prop(5, "sol_mom", "Solana Momentum", "Follow Solana tokens on 24h board.", { mode: "chain_follow", chain: "solana", window: "24h" }),
  prop(6, "base_mom", "Base Momentum", "Follow Base tokens on 24h board.", { mode: "chain_follow", chain: "base", window: "24h" }),
  prop(7, "eth_mom", "ETH Momentum", "Follow ETH tokens on 24h board.", { mode: "chain_follow", chain: "ethereum", window: "24h" }),
  prop(8, "fresh", "Fresh Board Tokens", "Prefer tokens only on 24h not 30d.", { mode: "fresh_tokens" }),
  prop(9, "sticky", "Sticky Tokens", "Tokens on 24h and 30d boards.", { mode: "sticky_tokens" }),
  prop(10, "max_val", "Value Whale Bags", "Buy highest USD-value holdings.", { mode: "max_value" }),
  prop(11, "min_val", "Micro Bags", "Buy smallest positive-value bags.", { mode: "min_value" }),
  prop(12, "low_px", "Low Price Spec", "Prefer cheaper tokens.", { mode: "low_price", maxPrice: 0.01 }),
  prop(13, "mid_px", "Mid Price", "Tokens between $0.01–$1.", { mode: "price_band", lo: 0.01, hi: 1 }),
  prop(14, "hi_px", "High Price", "Tokens above $1.", { mode: "high_price", minPrice: 1 }),
  prop(15, "rotate", "Rotate Winners", "Buy best pnl, sell worst held.", { mode: "rotate_winners" }),
  prop(16, "crowd_mr", "Crowd Mean Revert", "Fade most-held, buy least-held.", { mode: "crowd_mr" }),
  prop(17, "single", "Single Focus", "Max one position.", { mode: "single_focus" }),
  prop(18, "max3", "Max Three Books", "Cap 3 open tokens.", { mode: "max_books", maxBooks: 3 }),
  prop(19, "max5", "Max Five Books", "Cap 5 open tokens.", { mode: "max_books", maxBooks: 5 }),
  prop(20, "deploy", "Always Deploy", "Keep cash working in top consensus.", { mode: "always_deploy" }),
  prop(21, "cash", "Cash Heavy", "Trade rarely, only strongest signal.", { mode: "cash_heavy", minHolders: 5 }),
  prop(22, "foll_w", "Follower-Weighted", "Weight tokens by holder followers.", { mode: "follower_weighted" }),
  prop(23, "active", "Trade-Active Leaders", "Tokens from high-trade traders.", { mode: "active_traders" }),
  prop(24, "select", "Selective Leaders", "Tokens from low-trade high-pnl traders.", { mode: "selective_traders" }),
  prop(25, "sol_fade", "Solana Fade", "Fade Solana crowded bags.", { mode: "chain_fade", chain: "solana" }),
  prop(26, "base_fade", "Base Fade", "Fade Base crowded bags.", { mode: "chain_fade", chain: "base" }),
  prop(27, "breadth_l", "Breadth Long", "Buy when many unique tokens on board.", { mode: "breadth_long" }),
  prop(28, "breadth_s", "Breadth Short", "Sell into narrow crowded tapes.", { mode: "breadth_short" }),
  prop(29, "top1", "Global Top Holding", "Always buy the single most-held token.", { mode: "global_top1" }),
  prop(30, "top3eq", "Top 3 Equal Weight", "Equal weight top 3 consensus tokens.", { mode: "top3_equal" }),
  prop(31, "rand", "Random Control", "Random eligible token.", { mode: "random" }),
  prop(32, "buy", "Always Buy Control", "Buy first eligible token.", { mode: "always_buy" }),
  prop(33, "sell", "Always Sell Control", "Sell when holding.", { mode: "always_sell" }),
  prop(34, "tp", "Take Profit 20%", "Trim +20% winners.", { mode: "take_profit", tp: 0.2 }),
  prop(35, "sl", "Stop Loss 20%", "Cut −20% losers.", { mode: "stop_loss", sl: 0.2 }),
  prop(36, "hold_w", "Hold Winners", "Only add to winners.", { mode: "hold_winners" }),
  prop(37, "cut_l", "Cut Losers", "Sell negative mark positions.", { mode: "cut_losers" }),
  prop(38, "rebal", "Equal Rebalance", "Nudge toward equal weights.", { mode: "rebalance_equal" }),
  prop(39, "ign_sol", "Ignore Solana", "Trade non-Solana only.", { mode: "ignore_chain", chain: "solana" }),
  prop(40, "only_sol", "Only Solana", "Trade Solana only.", { mode: "only_chain", chain: "solana" }),
  prop(41, "pnl_mom", "PnL Momentum", "Chase tokens with rising board pnl.", { mode: "pnl_momentum" }),
  prop(42, "vol", "Volume Proxy", "Prefer tokens from high-volume traders.", { mode: "volume_proxy" }),
  prop(43, "ctr_24", "Contrarian 24h", "Fade 24h consensus.", { mode: "contrarian_window", window: "24h" }),
  prop(44, "fol_30", "Follow 30d Consensus", "Buy monthly consensus.", { mode: "follow_window", window: "30d" }),
  prop(45, "pair", "Pair Rotate", "Alternate between top 2 tokens.", { mode: "pair_rotate" }),
  prop(46, "inv", "Inventory Balance", "Flatten skew when >1 bag.", { mode: "inventory_balance" }),
  prop(47, "new", "New Money Proxy", "24h tokens absent from all-time bags.", { mode: "new_money" }),
  prop(48, "old", "Old Money Proxy", "Tokens on all-time board bags.", { mode: "old_money" }),
  prop(49, "combo", "Follow Elite / Fade Crowd", "Buy sticky elite, fade 24h crowd.", { mode: "combo_elite_fade" }),
  prop(50, "dust", "Avoid Microdust", "Skip extremely low-priced dust.", { mode: "avoid_dust", minPrice: 1e-8 }),
];

export const ALL_STRATEGIES: StrategyDef[] = [...TRADER_STRATEGIES, ...PROP_STRATEGIES];

export function getStrategy(id: string) {
  return ALL_STRATEGIES.find((s) => s.id === id);
}
